version: "3"


services: 
  nodejs: 
    build:
      context: ./node
    environment:
      - NODE_ENV=development
    volumes:
      - ./node:/usr/app
    ports:
      - "3000:3000"
      - "4000:4000"
    command: "yarn start"
